# This workflow will install snakemake and TaxVAMB dependencies and run the TaxVAMB snakemake pipeline

name: TaxVAMB snakemake - runs daily

on:
  workflow_dispatch:
    inputs:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/pyproject.toml'
    - name: Download fixtures
      run: |
        wget https://www.dropbox.com/scl/fi/q54wfho3ultb0otq5z3rh/testset_snakemake.zip\?rlkey\=7tbsc2giff0s42ppdmeb706fa\&dl\=0 -O testset_snakemake.zip
        gzip -d testset_snakemake.zip
        ls -la
        ls -la testset_snakemake
        pwd
    # - uses: mamba-org/setup-micromamba@v1
    #   with:
    #     micromamba-version: '1.3.1-0'
    #     environment-file: environment.yml
    #     init-shell: >-
    #       bash
    #       powershell
    #     cache-environment: true
    #     post-cleanup: 'all'
    # - name: Import numpy in micromamba environment (bash)
    #   run: python -c "import numpy"
    #   shell: bash -el {0}
    # - name: Import numpy in micromamba environment (pwsh)
    #   run: python -c "import numpy"
    #   shell: pwsh
    # - name: Run custom command in micromamba environment
    #   run: pytest --version
    #   shell: micromamba-shell {0}
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install flake8 pytest
    #     pip install -e .

    # - name: Snakemake
    #   uses: snakemake/snakemake-github-action@v1.25.1
    #   with:
    #     directory: '.test'
    #     snakefile: 'workflow/Snakefile'
    #     args: '--lint'
